### ISSUE TITLE
Calling setHighValue method for the second time deface the Gauge

### ISSUE THREAD

**Issue by mhdr** [Paroca72/sc-widgets#10]
![gauge](https://cloud.githubusercontent.com/assets/10972572/25958068/f728256c-3684-11e7-8149-cc696463bfdd.gif)

**Comment by Paroca72** [comment]
Hello,

Thanks for your advise.. this issue is already treated..
I'll let you know soon..

Bye

**Comment by mhdr** [comment]
Hello Sam,
Thank you for your immediate response and follow up

Bye

**Comment by Paroca72** [comment]
Hello,

I realsed a new version 2.1.4 that should resolve your issue.. but I have some problem with jitpack.io and I don't know if can be downloaded through gradle..
Kindly if you can try to download from gradle or manually and let me know.

Sam

**Comment by mhdr** [comment]
Hello Sam,
I had no problem with jitpack.io and your new release resolved my issue.
Thanks for the good work.

**Comment by mhdr** [comment]
Hello Sam,
Now it seems that setOnDrawListener won't fire after the second call of setHighValue method.
Thanks in advance.

**Comment by mhdr** [comment]
Hello Sam,
It seems that you removed invalidate method and that is the reason ScDrawer.onDraw won't be called for the second time.
I manually called gauge.invalidate() to force calling onDraw again, it resolved my second issue but the first one (defacing the gauge) appeared again. 
Thanks

**Comment by Paroca72** [comment]
Hello,

I'm looking on this issue and the problem is still there.. when call "invalidate"..
If you try to use the below code inside your activity you will see no issue.. it seems "invalidate" cannot called when the component, I think, is still not showed or similar..

    @Override
    public boolean onTouchEvent(MotionEvent e) {
        Random rnd = new Random();

        // Find the components
        final ScArcGauge gauge = (ScArcGauge) this.findViewById(R.id.gauge);
        gauge.setHighValue(rnd.nextInt(100));

        return true;
    }

The procedure to draw the gradient is a quite complex because the gradient must follow the path and a generic path is not always circular.. so I must use a shader for obtain this result and I'm sure the problem is when apply the shader.

Please let me more time for try to resolve..

Bye

**Comment by Paroca72** [comment]
Hello,

Thanks for the patient.. 
Try to download the new version 2.1.5

At the end the problem was the android.graphics.Paint class that on set a new shader it same merge it with the old one.. I don't know!
PS: I tried to set to null before set the new one but nothing change.

I solved with a trick (not beauty but seems to work) creating a clone (local) from the original Paint (global) and apply the shader to the clone.
This is not a common way to procede because it is always better not create object inside the onDraw procedure but for now it is the unique solution than I see.

On my local test I not see problem of performance but please let me know after tried it.

Bye

**Comment by mhdr** [comment]
Hello Sam.
I picked up version 2.1.6 and it works like a charm and I have no performance issue.
Thanks for your help.

Bye
